import { compileUiOnlyCss } from './pipelines.ts';

let cache: Set<string> | undefined;

/** The set of selectors generated by compiling @perimeter/ui source alone.
 * Compiled once per process and cached — every caller (report + regression
 * test) attributes dev-only selectors to ui components the same way. */
async function uiSelectorSet(): Promise<Set<string>> {
  if (cache) return cache;
  const uiCss = await compileUiOnlyCss();
  cache = new Set(
    [...uiCss.matchAll(/(?<=^|\})\s*([^@{}]+)\{/g)].flatMap((m) =>
      m[1]!.split(',').map((s) => s.replace(/\s+/g, ' ').trim()),
    ),
  );
  return cache;
}

/** Of the given dev-only selector keys, those whose bare selector (the part
 * after the final `' :: '` atrule-context separator) is generated by
 * @perimeter/ui source alone — i.e. the H2-attributable subset that must be
 * absent from the dev/prod diff once the shipped bundle scans packages/ui/src. */
export async function uiAttributableSelectors(devOnly: string[]): Promise<string[]> {
  const uiSelectors = await uiSelectorSet();
  return devOnly.filter((s) => uiSelectors.has(s.split(' :: ').pop()!));
}
