import type {
  RegistrationEvent,
  RegistrationRoster,
  RegistrationSection,
  UseRegistrationEventResponse,
  UseRegistrationRosterResponse,
} from '@perimeter/api-hooks';

/** Family Night as `GET /api/registration/events/900001` describes it (abridged). */

function section(
  over: Partial<RegistrationSection> & Pick<RegistrationSection, 'key' | 'displayName' | 'event'>,
): RegistrationSection {
  return {
    relatedEventId: null,
    enableLabelHtml: null,
    instructionsHtml: null,
    buttonText: `Add ${over.displayName} registrant`,
    position: 1,
    showHouseholdPositionId: null,
    forGenderId: null,
    isParentEvent: false,
    product: {
      productId: 9001,
      name: over.displayName,
      descriptionHtml: null,
      basePrice: 0,
      depositPrice: null,
      groups: [],
    },
    form: null,
    open: true,
    closedReason: null,
    ...over,
  };
}

const evt = (eventId: number, title: string, minorRegistration: boolean) => ({
  eventId,
  title,
  startDate: '2026-09-27T18:00:00',
  endDate: '2026-09-27T20:00:00',
  meetingInstructionsHtml: null,
  minorRegistration,
  participantsExpected: null,
  remaining: null,
  registrationStart: null,
  registrationEnd: null,
  externalRegistrationUrl: null,
});

export const familyNight: RegistrationEvent = {
  eventId: 900001,
  title: 'Family Night',
  descriptionHtml: '<p>Family members split into their desired events.</p>',
  startDate: '2026-09-27T18:00:00',
  endDate: '2026-09-27T20:00:00',
  timeZone: 'America/New_York',
  congregationId: 1,
  imageUrl: '/api/event-image/900001',
  location: {
    name: 'Perimeter Church',
    addressLine1: '9500 Medlock Bridge Rd',
    addressLine2: null,
    city: 'Johns Creek',
    state: 'GA',
    postalCode: '30097',
    directionsUrl: 'https://maps.google.com/maps?daddr=9500%20Medlock%20Bridge%20Rd',
    rooms: [],
  },
  primaryContact: { displayName: 'Ryan Nickell', emailAddress: null },
  visibilityLevelId: 5,
  viewable: true,
  cancelled: false,
  externalRegistrationUrl: null,
  viewer: {
    signedIn: true,
    contactId: 684077,
    loginRequired: false,
    canGuestRegister: true,
    isStaff: false,
  },
  registrationOpen: true,
  sections: [
    section({
      key: 'related:101',
      relatedEventId: 101,
      displayName: 'Elementary + Early Years Focus',
      showHouseholdPositionId: 1,
      event: evt(900011, 'Elementary + Early Years Focus', false),
    }),
    section({
      key: 'related:103',
      relatedEventId: 103,
      displayName: 'Student Night of Worship (Grades 6-12)',
      enableLabelHtml: '<b>Registering a student?</b>',
      buttonText: 'Add a student',
      position: 3,
      event: {
        ...evt(900013, 'Student Night of Worship', true),
        participantsExpected: 100,
        remaining: 5,
      },
      product: {
        productId: 9003,
        name: 'Student Night of Worship',
        descriptionHtml: null,
        basePrice: 10,
        depositPrice: null,
        groups: [
          {
            productOptionGroupId: 7003,
            name: 'Discounts',
            descriptionHtml: null,
            required: false,
            mutuallyExclusive: false,
            noteLabel: null,
            formFieldId: null,
            omitFromSummary: false,
            exhausted: false,
            prices: [
              {
                productOptionPriceId: 8004,
                title: 'T-Shirt',
                price: 12,
                qtyAllowed: 3,
                minQty: 1,
                maxQty: 50,
                remaining: 7,
                attendingOnline: false,
                addsToGroupId: null,
                hidden: false,
                isPromo: false,
                sortOrder: 2,
              },
            ],
          },
        ],
      },
      form: {
        formId: 5003,
        title: 'Student Night of Worship',
        instructionsHtml: null,
        forceLogin: false,
        blockedByFileUpload: false,
        fileUploadFieldIds: [],
        fields: [
          {
            formFieldId: 6001,
            order: 0,
            label: 'Grade',
            alternateLabelHtml: null,
            fieldTypeId: 5,
            values: ['6th', '7th', '8th'],
            required: true,
            dependsOnFieldId: null,
            dependsOnValue: null,
            omitFromSummary: false,
            hasSideEffects: false,
          },
          {
            formFieldId: 6002,
            order: 1,
            label: 'Allergies?',
            alternateLabelHtml: null,
            fieldTypeId: 4,
            values: ['Yes', 'No'],
            required: true,
            dependsOnFieldId: null,
            dependsOnValue: null,
            omitFromSummary: false,
            hasSideEffects: false,
          },
          {
            formFieldId: 6003,
            order: 2,
            label: 'Allergy details',
            alternateLabelHtml: null,
            fieldTypeId: 2,
            values: [],
            required: true,
            dependsOnFieldId: 6002,
            dependsOnValue: 'Yes',
            omitFromSummary: false,
            hasSideEffects: false,
          },
        ],
      },
    }),
    section({
      key: 'related:104',
      relatedEventId: 104,
      displayName: 'Elementary Active (Grades K-5)',
      showHouseholdPositionId: 2,
      position: 4,
      event: evt(900014, 'Elementary Active', true),
    }),
  ],
};

export const canoHousehold: RegistrationRoster = {
  householdId: 591145,
  viewer: {
    contactId: 684077,
    firstName: 'Jen',
    lastName: 'Cano',
    email: 'jen@example.com',
    phone: '770-555-9730',
    address: {
      line1: '5088 Bridgeport Way',
      line2: null,
      city: 'Peachtree Corners',
      state: 'GA',
      postalCode: '30092',
    },
  },
  creatablePositionIds: [2, 3, 4],
  members: [
    {
      contactId: 684077,
      firstName: 'Jen',
      lastName: 'Cano',
      displayName: 'Cano, Jennifer',
      householdPositionId: 1,
      genderId: 2,
      dateOfBirth: '1984-03-09',
      age: 42,
      isMinorPosition: false,
      isViewer: true,
      hasParticipantRecord: true,
      eligibility: [
        {
          sectionKey: 'related:101',
          eligible: true,
          reason: null,
          existingEventParticipantId: null,
        },
        {
          sectionKey: 'related:103',
          eligible: false,
          reason: 'minors_only',
          existingEventParticipantId: null,
        },
        {
          sectionKey: 'related:104',
          eligible: false,
          reason: 'household_position',
          existingEventParticipantId: null,
        },
      ],
    },
    {
      contactId: 698112,
      firstName: 'William',
      lastName: 'Cano',
      displayName: 'Cano, William',
      householdPositionId: 2,
      genderId: 1,
      dateOfBirth: '2015-03-21',
      age: 11,
      isMinorPosition: true,
      isViewer: false,
      hasParticipantRecord: true,
      eligibility: [
        {
          sectionKey: 'related:101',
          eligible: false,
          reason: 'household_position',
          existingEventParticipantId: null,
        },
        {
          sectionKey: 'related:103',
          eligible: true,
          reason: null,
          existingEventParticipantId: null,
        },
        {
          sectionKey: 'related:104',
          eligible: true,
          reason: null,
          existingEventParticipantId: null,
        },
      ],
    },
    {
      contactId: 698113,
      firstName: 'Max',
      lastName: 'Cano',
      displayName: 'Cano, Max',
      householdPositionId: 2,
      genderId: 1,
      dateOfBirth: '2017-05-16',
      age: 9,
      isMinorPosition: true,
      isViewer: false,
      hasParticipantRecord: false,
      eligibility: [
        {
          sectionKey: 'related:101',
          eligible: false,
          reason: 'household_position',
          existingEventParticipantId: null,
        },
        {
          sectionKey: 'related:103',
          eligible: false,
          reason: 'already_registered',
          existingEventParticipantId: 555,
        },
        {
          sectionKey: 'related:104',
          eligible: true,
          reason: null,
          existingEventParticipantId: null,
        },
      ],
    },
  ],
};

export function envelope<T>(data: T): { success: true; data: T; meta: { cached: boolean } } {
  return { success: true, data, meta: { cached: false } };
}

export type EventEnvelope = UseRegistrationEventResponse;
export type RosterEnvelope = UseRegistrationRosterResponse;
