import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

interface ManifestEntry {
    slug: string;
    name: string;
    description: string;
    category: string;
    install: string;
    demoFile: string;
}

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const SITE_ROOT = resolve(SCRIPT_DIR, '..');
const REGISTRY_DIR = resolve(SITE_ROOT, '../../packages/registry');
const DEMO_DIR = join(REGISTRY_DIR, 'ui/perimeter');
const OUTPUT_DIR = join(SITE_ROOT, 'src/lib');
const MANIFEST = join(OUTPUT_DIR, 'demo-manifest.json');
const IMPORTS = join(OUTPUT_DIR, 'demo-imports.ts');

async function collect(): Promise<void> {
    const files = await readdir(DEMO_DIR);
    const demoFiles = files.filter((f) => f.endsWith('.demo.tsx')).sort();

    const manifest: ManifestEntry[] = [];
    for (const file of demoFiles) {
        const content = await readFile(join(DEMO_DIR, file), 'utf-8');
        const slug = file.replace('.demo.tsx', '');

        const nameMatch = content.match(/name:\s*"([^"]+)"/);
        const descMatch = content.match(/description:\s*"([^"]+)"/);
        const catMatch = content.match(/category:\s*"([^"]+)"/);
        const installMatch = content.match(/install:\s*"([^"]+)"/);
        if (!nameMatch || !descMatch || !catMatch || !installMatch) {
            console.warn(`Skipping ${file}: missing meta fields`);
            continue;
        }

        manifest.push({
            slug,
            name: nameMatch[1]!,
            description: descMatch[1]!,
            category: catMatch[1]!,
            install: installMatch[1]!,
            demoFile: `@perimeter-widgets/registry/ui/perimeter/${slug}.demo`,
        });
    }

    manifest.sort(
        (a, b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name),
    );

    await mkdir(OUTPUT_DIR, { recursive: true });
    await writeFile(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');
    console.log(`Collected ${manifest.length} demo(s) → ${MANIFEST}`);

    const header = `// Auto-generated by apps/site/scripts/collect-demos.ts — do not edit manually\n\n`;
    const typeImport = `import type { ControlsConfig, DemoExample, DemoMeta } from '@/lib/demo-types';\n\n`;
    const moduleInterface = [
        'export interface DemoModule {',
        '    meta: DemoMeta;',
        '    controls: ControlsConfig;',
        '    Playground: React.ComponentType<Record<string, unknown>>;',
        '    examples: DemoExample[];',
        '}',
        '',
    ].join('\n');
    const lines = manifest.map(
        (entry) =>
            `    '${entry.slug}': () => import('@perimeter-widgets/registry/ui/perimeter/${entry.slug}.demo') as unknown as Promise<DemoModule>,`,
    );
    const body = [
        '// Each demo exports a Playground typed to its specific controls config.',
        '// We widen via assertion so all demos share the DemoModule interface.',
        'export const demoImports: Record<string, () => Promise<DemoModule>> = {',
        ...lines,
        '};',
        '',
    ].join('\n');

    await writeFile(IMPORTS, header + typeImport + moduleInterface + '\n' + body);
    console.log(`Wrote ${manifest.length} imports → ${IMPORTS}`);
}

collect().catch((err) => {
    console.error('collect-demos failed:', err);
    process.exit(1);
});
