import { useQuery, type UseQueryResult } from '@tanstack/react-query';
import { useApiClient } from '@perimeter/widget-runtime';
import { fetchJson } from '../internal/fetch-json';

/**
 * NOTE — hand-written types, pending the perimeter-api endpoint.
 *
 * Every other hook in this package derives its types from
 * `../generated/operations` (regenerated by `pnpm --filter @perimeter/api-hooks
 * sync` from perimeter-api's `openapi/spec.yaml`). `GET /api/missions/my-trips`
 * does not exist yet, so there is no operation to derive from and the shape
 * below is declared by hand.
 *
 * The shape is the contract the endpoint must satisfy. It is the *normalized*
 * form the legacy widget used to assemble in the browser: the old
 * `api_custom_MyMissionTrips_Current` stored procedure returned nine parallel
 * datasets (pledges, donors, leader trips, leader participants, letters,
 * leader info, past trips, past leader info, past donors) which the widget
 * cross-joined client-side on `Pledge_ID`/`Pledge_Campaign_ID`. That merge
 * belongs in the service layer, so this hook expects one flat list of trips
 * with donations, participants and leaders already nested.
 *
 * When the endpoint lands, replace these declarations with
 * `operations['getMyMissionTrips']['responses']['200']…` and delete this note.
 */

/** A household mailing address on a donation row. */
export interface MyMissionAddress {
  line1: string | null;
  line2: string | null;
  city: string | null;
  state: string | null;
  postalCode: string | null;
}

/**
 * One gift toward a participant's trip pledge.
 *
 * Covers both hard credit and soft credit (the legacy SP UNION'd
 * `Donation_Distributions` on `Donor_ID` and on `Soft_Credit_Donor`). When
 * `anonymous` is true the server must omit the donor's identity and contact
 * details rather than sending them for the client to hide.
 */
export interface MyMissionDonation {
  /** Donation date as an ISO-8601 string. */
  date: string;
  amount: number;
  anonymous: boolean;
  /** Rendered "nickname lastname", or `"Anonymous"` when `anonymous`. */
  donorName: string;
  email: string | null;
  phone: string | null;
  address: MyMissionAddress | null;
}

/** A fellow participant on a trip the viewer leads. */
export interface MyMissionParticipant {
  pledgeId: number;
  /** Rendered "nickname lastname". */
  name: string;
  email: string | null;
  totalPledge: number;
  totalDonations: number;
}

/** A trip leader shown in the trip's Leaders strip. */
export interface MyMissionLeader {
  name: string;
  email: string | null;
  photoUrl: string | null;
}

/** Whole-trip funding totals, present only when the viewer leads the trip. */
export interface MyMissionLeaderSummary {
  /** The viewer's own leader email — the From address for "Email All". */
  email: string | null;
  /** Raised across every active pledge on the campaign. */
  totalDonations: number;
  /** Sum of every active pledge's goal on the campaign. */
  totalGoal: number;
}

/**
 * One mission trip pledge belonging to the viewer or — when the viewer is the
 * head of their household — to a household member.
 *
 * The grain is a **pledge**, not a campaign: two household members on the same
 * trip are two rows sharing a `campaignId`, which is why `participantName`
 * matters for disambiguation.
 */
export interface MyMissionTrip {
  pledgeId: number;
  campaignId: number;
  /** `Pledge_Campaigns.Nickname`, falling back to "Destination: start – end". */
  name: string;
  /** Rich-text HTML from `Pledge_Campaigns.Long_Description`. */
  longDescription: string | null;
  /** Trip start/end as ISO-8601 strings. */
  startDate: string;
  endDate: string;
  /** True for a trip that has already ended (the legacy "Past Trips" list). */
  past: boolean;
  /**
   * True when the pledge is the viewer's own. False for a household member's
   * pledge surfaced because the viewer is head of household.
   */
  mine: boolean;
  /** Whose pledge this is, rendered "nickname lastname". */
  participantName: string;
  /** `Pledge_Statuses.Pledge_Status` label. */
  pledgeStatus: string;
  totalPledge: number;
  totalDonations: number;
  /** Most recent gift date as ISO-8601, or `null` when nothing has come in. */
  lastDonationDate: string | null;
  /** The participant's support letter as HTML. `null` on past trips. */
  letter: string | null;
  /** True when this participant is a trip leader. */
  isLeader: boolean;
  leaders: MyMissionLeader[];
  donations: MyMissionDonation[];
  /** `null` unless the viewer leads this trip. */
  leaderSummary: MyMissionLeaderSummary | null;
  /** Empty unless the viewer leads this trip. */
  participants: MyMissionParticipant[];
}

export interface UseMyMissionTripsResponse {
  data: {
    trips: MyMissionTrip[];
  };
}

/**
 * The signed-in user's mission trips — their own pledges plus, when they are
 * head of household, their household members'.
 *
 * Authenticated with no params: the bearer token is attached by the api-client
 * from the widget's auth provider and the endpoint derives the donor and
 * household entirely from it, so a user can never read another household's
 * trips. Left at the QueryClient default stale time — donation totals move
 * during a campaign, so this is content, not a facet list.
 */
export function useMyMissionTrips(options?: {
  enabled?: boolean;
}): UseQueryResult<UseMyMissionTripsResponse> {
  const client = useApiClient();
  return useQuery({
    queryKey: ['my-mission-trips'],
    enabled: options?.enabled ?? true,
    queryFn: () =>
      fetchJson<UseMyMissionTripsResponse>(client, '/api/missions/my-trips', 'My mission trips'),
  });
}
